
name: Build and test serial backend of VecOps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    # checks out the code in the repository
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++

    - name: Build and test
      working-directory: ${{ github.workspace }}
      run: |
        cmake -B build -Dtesting=ON
        cmake --build build -- -j4
        ./build/testx/Boost 100 100
        ./build/testx/InvariantMasses 100 100

